---
rewards:
 - "1:0:1" # Id:Meta:Count

reward-count-min: 1 # The min amount of rewards a player can get.
reward-count-max: 5 # The max amount of rewards a player can get.

chance: 100 # Chance of getting reward
...